implementation of the puncher
jfssvex/challenge-2022-a pull request #14
Opened 2022-05-07 02:41 UTC by hariskhawja

unfinished and planned to be completed soon
errors: redefinition of Puncher and function calling error for SystemManager

2022-05-07 16:31 UTC, AritroSaha10 commented on include/puncherManager.h
> +        Puncher(pros::Motor *puncher) {};
The brackets create a blank definition of the class, hence the redefinition error. By removing these, the error should be gone.

2022-05-07 16:31 UTC, AritroSaha10 commented on include/puncherManager.h
> +        virtual void windUp();
These don't need to be virtual because we're already defining them in the current class

2022-05-07 16:31 UTC, AritroSaha10 commented on src/puncher.cpp
> +    void Puncher::windUp() {
These function definitions should be outside the puncher initialization class

2022-05-07 16:31 UTC, AritroSaha10 commented on src/puncher.cpp
> +        this->puncher->windUp(-100);
The motor functions don't include windUp or punch, and would likely error out

2022-05-07 16:31 UTC, AritroSaha10 commented on include/puncherManager.h
> +        Puncher(pros::Motor *puncher) {};
In addition, the initializer should also include `uint8_t defaultState` as a parameter because of the base class.

2022-05-07 16:31 UTC, AritroSaha10 commented on include/puncherManager.h
> +        /**
You will probably want to add a few static constant states specific to the puncher (ex. winding up, neutral)

2022-05-07 17:19 UTC, hariskhawja commented on src/puncher.cpp
> +    void Puncher::windUp() {
Then where should they be declared if not within this class?

2022-05-07 17:27 UTC, AritroSaha10 commented on src/puncher.cpp
> +    void Puncher::windUp() {
Outside of the class, since each of the functions (incl. constructor) are different.

Example:

```cpp
Puncher::Puncher(params) {
    <code>
}

void Puncher::windUp() {
    <code>
}
```

2022-05-07 20:45 UTC, hariskhawja commented on include/puncherManager.h
> +        /**
True, what should I equate the constants to?

2022-05-07 20:59 UTC, AritroSaha10 commented on include/puncherManager.h
> +        /**
I already answered this in a call, but just for the sake of keeping it for later, it's basically any random number that doesn't conflict with the values of current states (for now, the ones in the base SystemManager class).

2022-05-07 22:01 UTC, hariskhawja commented on src/puncher.cpp
> +Puncher::Puncher(uint8_t state, pros::Motor *puncher) {
the "no default constructor exists for class SystemManager" occurs here

2022-05-07 23:24 UTC, AritroSaha10 commented on src/puncher.cpp
> +Puncher::Puncher(uint8_t state, pros::Motor *puncher) {
Change L11 to `Puncher::Puncher(uint8_t state, pros::Motor *puncher): SystemManager(state)`

2022-05-09 23:09 UTC, AritroSaha10 commented on include/chassis.h
> +#define PUN_PORT 10
Can you change this to `PUNCHER_PORT`?

2022-05-09 23:09 UTC, AritroSaha10 requested changes
Looks great! Just one small thing to fix and it should be ready to merge

2022-05-10 17:17 UTC, merged

2022-05-10 17:17 UTC, AritroSaha10 commented
Merged!