Created drivetrain.h
jfssvex/challenge-2022-a pull request #3
Opened 2022-04-15 03:06 UTC by hariskhawja

2022-04-19 18:37 UTC, AritroSaha10 requested changes
Great! I just added a few things that should be changed. Also, I'm not sure if you were planning on doing this later, but since it's been a while since the last commit, could you also add some implementation for the `SkidSteerDrive` class?

2022-04-19 18:37 UTC, AritroSaha10 commented on include/driveSystems/SkidSteerDrive.h
> +        // bRight --> bottom right motor
Can you change the function header comments to follow JavaDoc? It directly integrates with both IntelliSense and Doxygen Here's an example for the constructor:

```c++
/**
 * \brief Constructor for SkidSteerDrive class
 * 
 * \param tLeft top left motor
 * \param tRight top right motor
 * \param bLeft bottom left motor
 * \param bRight bottom right motor
*/
SkidSteerDrive(pros::Motor *tLeft, pros::Motor *tRight, pros::Motor *bLeft, pros::Motor *bRight);
```

2022-04-19 18:37 UTC, AritroSaha10 commented on include/driveSystems/SkidSteerDrive.h
> +        // to be reviewed; compiling issues with the vector?
Can you respond with the error that you're getting? I uncommented this part and it built normally.

2022-04-20 16:17 UTC, AritroSaha10 commented on include/driveSystems/SkidSteerDrive.h
> +        // bRight --> bottom right motor
Fixed in f24b0e93410a736ffcad486443ad47c237794f98

2022-04-20 16:18 UTC, AritroSaha10 commented
I added some jsdoc-style comments in f24b0e93410a736ffcad486443ad47c237794f98. All that's left is implementing the functions defined in SkidSteerDrive.

2022-04-20 20:10 UTC, hariskhawja commented
Oh thank you. I'll get to it as soon as possible

2022-04-25 14:20 UTC, AritroSaha10 commented
Looks good! Just one thing: function documentation is only necessary in header files, as they get auto-imported into the source files.

2022-04-25 14:21 UTC, AritroSaha10 approved these changes

2022-04-25 14:22 UTC, merged